// ============================================================
// data.js  –  Synthetic sample data for Supply Chain Assistant
// All data is fictional and generated for demonstration purposes
// ============================================================

/* ── DISRUPTION SCENARIOS ─────────────────────────────────── */
const DISRUPTION_SCENARIOS = {
  none: {
    id: "none",
    label: "No Active Disruption",
    type: "None",
    location: "—",
    severity: "None",
    severityLevel: 0,
    startTime: null,
    expectedDuration: "—",
    affectedRoutes: [],
    affectedCarriers: [],
    affectedShipmentIds: [],
    businessImpact: "Normal operations. No disruptions detected.",
    description: "All routes and carriers operating normally.",
    delayMultiplier: 0,
    riskBoost: 0,
    coldChainRisk: false,
  },
  severe_storm: {
    id: "severe_storm",
    label: "Severe Storm",
    type: "Weather",
    location: "Gulf of Mexico / Houston Port Area",
    severity: "Critical",
    severityLevel: 4,
    startTime: "2025-07-14 06:00 UTC",
    expectedDuration: "48–72 hours",
    affectedRoutes: ["I-10 West", "SR-87 Coastal", "Port Houston Gateway"],
    affectedCarriers: ["OceanFreight Co", "FastLane Trucking"],
    affectedShipmentIds: ["SHP-001", "SHP-003", "SHP-007", "SHP-010", "SHP-012"],
    businessImpact: "Estimated $2.4M revenue at risk. Cold-chain cargo at high temperature exposure risk.",
    description: "Category 3 storm making landfall. All coastal routes suspended. Inland alternatives recommended.",
    delayMultiplier: 2.5,
    riskBoost: 3,
    coldChainRisk: true,
  },
  port_strike: {
    id: "port_strike",
    label: "Port Strike",
    type: "Labour",
    location: "Port of Los Angeles / Long Beach",
    severity: "High",
    severityLevel: 3,
    startTime: "2025-07-13 00:00 UTC",
    expectedDuration: "5–10 days",
    affectedRoutes: ["I-710 South", "SR-47 Port Access", "Pacific Container Lane"],
    affectedCarriers: ["PacificShip Lines", "WestCoast Freight"],
    affectedShipmentIds: ["SHP-002", "SHP-005", "SHP-008", "SHP-011"],
    businessImpact: "Estimated $1.8M in delayed consignments. Electronics and perishables most affected.",
    description: "Dockworkers union strike at LA/LB ports. All container unloading halted. Divert to Port of Oakland or San Diego.",
    delayMultiplier: 1.8,
    riskBoost: 2,
    coldChainRisk: false,
  },
  highway_closure: {
    id: "highway_closure",
    label: "Highway Closure",
    type: "Infrastructure",
    location: "I-80 Nebraska Corridor",
    severity: "Medium",
    severityLevel: 2,
    startTime: "2025-07-14 08:00 UTC",
    expectedDuration: "24–36 hours",
    affectedRoutes: ["I-80 Eastbound", "US-30 Parallel"],
    affectedCarriers: ["MidWest Haulers", "CrossCountry Express"],
    affectedShipmentIds: ["SHP-004", "SHP-006", "SHP-009"],
    businessImpact: "Estimated $450K delay cost. Auto parts and retail goods affected.",
    description: "Bridge structural damage on I-80 near Grand Island, NE. Closed indefinitely pending inspection.",
    delayMultiplier: 1.4,
    riskBoost: 1,
    coldChainRisk: false,
  },
  geopolitical: {
    id: "geopolitical",
    label: "Geopolitical Restriction",
    type: "Regulatory",
    location: "US–Mexico Border / Laredo, TX",
    severity: "High",
    severityLevel: 3,
    startTime: "2025-07-12 00:00 UTC",
    expectedDuration: "Unknown",
    affectedRoutes: ["I-35 Border Crossing", "Columbia Bridge Route"],
    affectedCarriers: ["BorderXpress", "TransAm Logistics"],
    affectedShipmentIds: ["SHP-003", "SHP-007", "SHP-012"],
    businessImpact: "Estimated $3.1M in cross-border shipments at risk. Customs clearance delays expected.",
    description: "Enhanced customs inspections and temporary trade restrictions at Laredo crossings. Significant processing delays.",
    delayMultiplier: 2.0,
    riskBoost: 2,
    coldChainRisk: true,
  },
  extreme_heat: {
    id: "extreme_heat",
    label: "Extreme Heat",
    type: "Weather",
    location: "Phoenix, AZ / Sonoran Desert Corridor",
    severity: "High",
    severityLevel: 3,
    startTime: "2025-07-14 10:00 UTC",
    expectedDuration: "72+ hours",
    affectedRoutes: ["I-10 Arizona", "US-60 Phoenix Metro", "SR-85 Southern"],
    affectedCarriers: ["SunState Carriers", "ArizonaFreight Co"],
    affectedShipmentIds: ["SHP-002", "SHP-006", "SHP-010"],
    businessImpact: "Estimated $900K cold-chain cargo at critical temperature risk. Driver safety restrictions apply.",
    description: "Temperatures exceeding 118°F. Cold-chain integrity severely compromised. Hours of service restrictions for drivers.",
    delayMultiplier: 1.6,
    riskBoost: 2,
    coldChainRisk: true,
  },
};

/* ── SHIPMENTS ─────────────────────────────────────────────── */
const SHIPMENTS_DATA = [
  {
    id: "SHP-001",
    origin: "Houston, TX",
    destination: "Atlanta, GA",
    cargoType: "Pharmaceuticals",
    carrier: "OceanFreight Co",
    currentRoute: "I-10 West → I-20 East",
    eta: "2025-07-16 14:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "Critical",
    riskLevel: "Low",
    tempRequired: "2–8°C",
    coldChain: true,
    status: "On Time",
    recommendedAction: "Monitor temperature sensors",
    weight: "4,200 kg",
    value: "$380,000",
  },
  {
    id: "SHP-002",
    origin: "Los Angeles, CA",
    destination: "Chicago, IL",
    cargoType: "Electronics",
    carrier: "PacificShip Lines",
    currentRoute: "I-710 South → I-10 East",
    eta: "2025-07-17 09:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "High",
    riskLevel: "Medium",
    tempRequired: "15–25°C",
    coldChain: false,
    status: "On Time",
    recommendedAction: "Track carrier updates",
    weight: "8,500 kg",
    value: "$1,200,000",
  },
  {
    id: "SHP-003",
    origin: "Laredo, TX",
    destination: "Dallas, TX",
    cargoType: "Automotive Parts",
    carrier: "BorderXpress",
    currentRoute: "I-35 North → I-35E",
    eta: "2025-07-15 11:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "High",
    riskLevel: "Low",
    tempRequired: "Ambient",
    coldChain: false,
    status: "On Time",
    recommendedAction: "Confirm border clearance",
    weight: "12,000 kg",
    value: "$650,000",
  },
  {
    id: "SHP-004",
    origin: "Denver, CO",
    destination: "New York, NY",
    cargoType: "Retail Goods",
    carrier: "MidWest Haulers",
    currentRoute: "I-80 East → I-78 East",
    eta: "2025-07-18 16:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "Medium",
    riskLevel: "Low",
    tempRequired: "Ambient",
    coldChain: false,
    status: "On Time",
    recommendedAction: "Standard monitoring",
    weight: "18,000 kg",
    value: "$290,000",
  },
  {
    id: "SHP-005",
    origin: "Long Beach, CA",
    destination: "Seattle, WA",
    cargoType: "Consumer Electronics",
    carrier: "WestCoast Freight",
    currentRoute: "I-5 North → SR-520",
    eta: "2025-07-16 08:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "High",
    riskLevel: "Low",
    tempRequired: "10–30°C",
    coldChain: false,
    status: "On Time",
    recommendedAction: "Standard monitoring",
    weight: "6,300 kg",
    value: "$920,000",
  },
  {
    id: "SHP-006",
    origin: "Phoenix, AZ",
    destination: "Albuquerque, NM",
    cargoType: "Fresh Produce",
    carrier: "SunState Carriers",
    currentRoute: "I-10 East → I-25 North",
    eta: "2025-07-15 07:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "Critical",
    riskLevel: "Medium",
    tempRequired: "4–10°C",
    coldChain: true,
    status: "On Time",
    recommendedAction: "Monitor cold chain",
    weight: "9,000 kg",
    value: "$120,000",
  },
  {
    id: "SHP-007",
    origin: "Monterrey, MX",
    destination: "San Antonio, TX",
    cargoType: "Industrial Equipment",
    carrier: "TransAm Logistics",
    currentRoute: "Columbia Bridge → I-35 North",
    eta: "2025-07-15 15:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "Medium",
    riskLevel: "Low",
    tempRequired: "Ambient",
    coldChain: false,
    status: "On Time",
    recommendedAction: "Verify customs docs",
    weight: "22,000 kg",
    value: "$480,000",
  },
  {
    id: "SHP-008",
    origin: "Oakland, CA",
    destination: "Las Vegas, NV",
    cargoType: "Food & Beverage",
    carrier: "PacificShip Lines",
    currentRoute: "I-580 East → I-15 South",
    eta: "2025-07-15 20:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "High",
    riskLevel: "Low",
    tempRequired: "0–4°C",
    coldChain: true,
    status: "On Time",
    recommendedAction: "Standard monitoring",
    weight: "7,200 kg",
    value: "$95,000",
  },
  {
    id: "SHP-009",
    origin: "Omaha, NE",
    destination: "Cleveland, OH",
    cargoType: "Auto Parts",
    carrier: "CrossCountry Express",
    currentRoute: "I-80 East → I-76 East",
    eta: "2025-07-16 12:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "Medium",
    riskLevel: "Low",
    tempRequired: "Ambient",
    coldChain: false,
    status: "On Time",
    recommendedAction: "Standard monitoring",
    weight: "14,500 kg",
    value: "$310,000",
  },
  {
    id: "SHP-010",
    origin: "Houston, TX",
    destination: "Miami, FL",
    cargoType: "Chemicals",
    carrier: "FastLane Trucking",
    currentRoute: "I-10 East → I-75 South",
    eta: "2025-07-17 18:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "Critical",
    riskLevel: "Medium",
    tempRequired: "15–20°C",
    coldChain: true,
    status: "On Time",
    recommendedAction: "Hazmat compliance check",
    weight: "5,800 kg",
    value: "$560,000",
  },
  {
    id: "SHP-011",
    origin: "San Diego, CA",
    destination: "Portland, OR",
    cargoType: "Medical Supplies",
    carrier: "WestCoast Freight",
    currentRoute: "I-5 North → OR-217",
    eta: "2025-07-16 10:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "Critical",
    riskLevel: "Low",
    tempRequired: "2–8°C",
    coldChain: true,
    status: "On Time",
    recommendedAction: "Priority clearance",
    weight: "3,100 kg",
    value: "$720,000",
  },
  {
    id: "SHP-012",
    origin: "McAllen, TX",
    destination: "Kansas City, MO",
    cargoType: "Perishable Goods",
    carrier: "OceanFreight Co",
    currentRoute: "US-83 North → I-35 North → I-70 East",
    eta: "2025-07-16 22:00",
    baseDelay: 0,
    delayHours: 0,
    priority: "High",
    riskLevel: "Medium",
    tempRequired: "−18 to −15°C",
    coldChain: true,
    status: "On Time",
    recommendedAction: "Monitor frozen chain",
    weight: "6,700 kg",
    value: "$145,000",
  },
];

/* ── ROUTE OPTIONS ─────────────────────────────────────────── */
const ROUTE_OPTIONS = {
  "SHP-001": [
    { type: "current",     name: "I-10 West → I-20 East",         distance: "790 mi", time: "13h",  addCost: "$0",    delayReduction: "0h",  risk: 4, weather: "Severe Storm", road: "Closed",   carrier: "Unavailable", fuel: "Baseline",   score: 2  },
    { type: "recommended", name: "I-45 North → I-20 East (Alt)",   distance: "820 mi", time: "14h",  addCost: "+$180", delayReduction: "18h", risk: 1, weather: "Clear",        road: "Good",      carrier: "Available",   fuel: "+8%",        score: 9  },
    { type: "emergency",   name: "US-190 East → US-84 East",       distance: "870 mi", time: "15h",  addCost: "+$320", delayReduction: "20h", risk: 2, weather: "Cloudy",       road: "Fair",      carrier: "Available",   fuel: "+14%",       score: 7  },
  ],
  "SHP-002": [
    { type: "current",     name: "I-710 South → I-10 East",        distance: "2,020 mi", time: "32h", addCost: "$0",    delayReduction: "0h",  risk: 5, weather: "Port Strike",  road: "Blocked",   carrier: "Unavailable", fuel: "Baseline",   score: 1  },
    { type: "recommended", name: "US-101 North → I-5 North → I-84",distance: "2,100 mi", time: "34h", addCost: "+$240", delayReduction: "24h", risk: 2, weather: "Clear",        road: "Good",      carrier: "Available",   fuel: "+10%",       score: 8  },
    { type: "emergency",   name: "Air Freight – LAX to ORD",        distance: "N/A",      time: "6h",  addCost: "+$3,800",delayReduction:"30h", risk: 1, weather: "Clear",        road: "N/A",       carrier: "Available",   fuel: "N/A",        score: 6  },
  ],
  "SHP-003": [
    { type: "current",     name: "I-35 North → I-35E",             distance: "280 mi", time: "5h",   addCost: "$0",    delayReduction: "0h",  risk: 5, weather: "Restriction",  road: "Restricted",carrier: "Delayed",     fuel: "Baseline",   score: 1  },
    { type: "recommended", name: "US-277 North → US-87 North",      distance: "310 mi", time: "6h",   addCost: "+$90",  delayReduction: "12h", risk: 2, weather: "Clear",        road: "Good",      carrier: "Available",   fuel: "+6%",        score: 9  },
    { type: "emergency",   name: "I-10 East → I-20 East → I-35N",  distance: "380 mi", time: "7h",   addCost: "+$160", delayReduction: "10h", risk: 3, weather: "Clear",        road: "Good",      carrier: "Available",   fuel: "+18%",       score: 6  },
  ],
  "default": [
    { type: "current",     name: "Current Assigned Route",          distance: "—",      time: "—",    addCost: "$0",    delayReduction: "0h",  risk: 3, weather: "Normal",       road: "Good",      carrier: "Available",   fuel: "Baseline",   score: 5, vehicleAvailability: "Standard Fleet", deliveryDeadline: "Deadline at risk", rationale: "Baseline route. Subject to active disruption delays along primary corridor."  },
    { type: "recommended", name: "Optimised Alternative Route",     distance: "—",      time: "—",    addCost: "+$150", delayReduction: "8h",  risk: 1, weather: "Clear",        road: "Good",      carrier: "Available",   fuel: "+5%",        score: 8, vehicleAvailability: "VH-106 Available", deliveryDeadline: "On-Time (6h buffer)", rationale: "Recommended bypass route minimizing disruption exposure, leveraging nearby available fleet asset to ensure on-time delivery."  },
    { type: "emergency",   name: "Emergency Contingency Route",     distance: "—",      time: "—",    addCost: "+$400", delayReduction: "12h", risk: 2, weather: "Clear",        road: "Fair",      carrier: "Available",   fuel: "+15%",       score: 6, vehicleAvailability: "High-cost Express", deliveryDeadline: "On-Time (10h buffer)", rationale: "Emergency expedited routing. Guarantees tightest delivery window but incurs high fuel and toll surcharges."  },
  ],
};

/* ── CARRIERS ──────────────────────────────────────────────── */
const CARRIERS_DATA = [
  { id: "C-01", name: "Arctic Express Logistics",  capacity: "8,000 kg", reliability: 96, cost: "$2,800", transitTime: "24h", region: "National",      coldChain: true,  risk: "Low",    reason: "Top-rated cold-chain specialist with 96% on-time record." },
  { id: "C-02", name: "RapidRoute USA",            capacity: "15,000 kg",reliability: 91, cost: "$1,950", transitTime: "36h", region: "Continental US",coldChain: false, risk: "Low",    reason: "High capacity, reliable, cost-effective for dry cargo." },
  { id: "C-03", name: "NorthStar Freight",         capacity: "12,000 kg",reliability: 88, cost: "$2,200", transitTime: "30h", region: "North & East",  coldChain: true,  risk: "Medium", reason: "Available now; strong northern corridor performance." },
  { id: "C-04", name: "Pinnacle Air Cargo",        capacity: "5,000 kg", reliability: 99, cost: "$7,400", transitTime: "8h",  region: "National",      coldChain: true,  risk: "Low",    reason: "Fastest available option. Premium cost justified for critical cargo." },
  { id: "C-05", name: "GreatPlains Haulage",       capacity: "22,000 kg",reliability: 85, cost: "$1,600", transitTime: "48h", region: "Midwest",       coldChain: false, risk: "Medium", reason: "Best capacity option for bulk non-refrigerated cargo." },
];

/* ── DRIVERS DATA ──────────────────────────────────────────── */
const DRIVERS_DATA = [
  { id: "DRV-01", name: "Marcus Vance",     license: "Class A CDL + Hazmat", location: "Dallas, TX",       hoursDriven7d: 32, maxHours7d: 56, status: "Available",   assignedAsset: null,     experienceYears: 12, rating: 4.9 },
  { id: "DRV-02", name: "Sarah Jenkins",    license: "Class A CDL (Reefer)",  location: "Phoenix, AZ",      hoursDriven7d: 18, maxHours7d: 56, status: "Available",   assignedAsset: null,     experienceYears: 8,  rating: 4.8 },
  { id: "DRV-03", name: "Carlos Rodriguez", license: "Class A CDL + Tanker", location: "Houston, TX",      hoursDriven7d: 48, maxHours7d: 56, status: "On Duty",     assignedAsset: "VH-103", experienceYears: 15, rating: 4.7 },
  { id: "DRV-04", name: "David Chen",       license: "Class A CDL",          location: "Memphis, TN",      hoursDriven7d: 22, maxHours7d: 56, status: "Available",   assignedAsset: null,     experienceYears: 6,  rating: 4.6 },
  { id: "DRV-05", name: "Elena Rostova",    license: "Class B CDL",          location: "Omaha, NE",        hoursDriven7d: 14, maxHours7d: 56, status: "Available",   assignedAsset: null,     experienceYears: 5,  rating: 4.9 },
  { id: "DRV-06", name: "Jamal Washington", license: "Class A CDL (Heavy)",   location: "Kansas City, MO",  hoursDriven7d: 26, maxHours7d: 56, status: "Available",   assignedAsset: null,     experienceYears: 10, rating: 4.8 },
  { id: "DRV-07", name: "Anita Patel",      license: "Class A CDL (Reefer)",  location: "San Diego, CA",    hoursDriven7d: 42, maxHours7d: 56, status: "On Duty",     assignedAsset: "VH-107", experienceYears: 9,  rating: 4.9 },
  { id: "DRV-08", name: "Robert Miller",    license: "Class A CDL",          location: "Los Angeles, CA",  hoursDriven7d: 40, maxHours7d: 56, status: "On Duty",     assignedAsset: "VH-105", experienceYears: 14, rating: 4.7 },
];

/* ── FLEET ASSETS ──────────────────────────────────────────── */
const FLEET_DATA = [
  { id: "VH-101", type: "Refrigerated Truck",  location: "Dallas, TX",       lat: 32.7767, lon: -96.7970, capacity: "8,000 kg",  capacityKg: 8000, currentLoad: "6,400 kg", loadKg: 6400, utilisation: 80, driver: "DRV-01", driverName: "Marcus Vance",     fuel: 72, tempCapable: true,  status: "In Transit",  nearestAffected: "SHP-001", redeployDistance: "140 mi", redeployTime: "3h", assignments30d: 8,  idleDays: 0 },
  { id: "VH-102", type: "Flatbed Truck",        location: "Memphis, TN",      lat: 35.1495, lon: -90.0490, capacity: "18,000 kg", capacityKg: 18000,currentLoad: "0 kg",     loadKg: 0,    utilisation: 0,  driver: "DRV-04", driverName: "David Chen",       fuel: 91, tempCapable: false, status: "Idle",        nearestAffected: "SHP-004", redeployDistance: "380 mi", redeployTime: "6h", assignments30d: 1,  idleDays: 5 },
  { id: "VH-103", type: "Tanker Truck",         location: "Houston, TX",      lat: 29.7604, lon: -95.3698, capacity: "10,000 kg", capacityKg: 10000,currentLoad: "9,600 kg", loadKg: 9600, utilisation: 96, driver: "DRV-03", driverName: "Carlos Rodriguez", fuel: 55, tempCapable: false, status: "In Transit",  nearestAffected: "SHP-010", redeployDistance: "0 mi",   redeployTime: "0h", assignments30d: 11, idleDays: 0 },
  { id: "VH-104", type: "Refrigerated Van",     location: "Phoenix, AZ",      lat: 33.4484, lon: -112.0740,capacity: "4,500 kg",  capacityKg: 4500, currentLoad: "0 kg",     loadKg: 0,    utilisation: 0,  driver: "DRV-02", driverName: "Sarah Jenkins",    fuel: 88, tempCapable: true,  status: "Idle",        nearestAffected: "SHP-006", redeployDistance: "20 mi",  redeployTime: "1h", assignments30d: 2,  idleDays: 4 },
  { id: "VH-105", type: "Dry Van Truck",        location: "Los Angeles, CA",  lat: 34.0522, lon: -118.2437,capacity: "20,000 kg", capacityKg: 20000,currentLoad: "14,000 kg",loadKg: 14000,utilisation: 70, driver: "DRV-08", driverName: "Robert Miller",    fuel: 63, tempCapable: false, status: "In Transit",  nearestAffected: "SHP-002", redeployDistance: "0 mi",   redeployTime: "0h", assignments30d: 7,  idleDays: 0 },
  { id: "VH-106", type: "Box Truck",            location: "Omaha, NE",        lat: 41.2565, lon: -95.9345, capacity: "6,000 kg",  capacityKg: 6000, currentLoad: "0 kg",     loadKg: 0,    utilisation: 0,  driver: "DRV-05", driverName: "Elena Rostova",    fuel: 95, tempCapable: false, status: "Available",   nearestAffected: "SHP-009", redeployDistance: "10 mi",  redeployTime: "0.5h",assignments30d: 1,  idleDays: 2 },
  { id: "VH-107", type: "Refrigerated Truck",  location: "San Diego, CA",    lat: 32.7157, lon: -117.1611,capacity: "9,000 kg",  capacityKg: 9000, currentLoad: "7,200 kg", loadKg: 7200, utilisation: 80, driver: "DRV-07", driverName: "Anita Patel",      fuel: 44, tempCapable: true,  status: "In Transit",  nearestAffected: "SHP-011", redeployDistance: "0 mi",   redeployTime: "0h", assignments30d: 9,  idleDays: 0 },
  { id: "VH-108", type: "Heavy Hauler",         location: "Kansas City, MO",  lat: 39.0997, lon: -94.5786, capacity: "30,000 kg", capacityKg: 30000,currentLoad: "0 kg",     loadKg: 0,    utilisation: 0,  driver: "DRV-06", driverName: "Jamal Washington", fuel: 78, tempCapable: false, status: "Idle",        nearestAffected: "SHP-012", redeployDistance: "250 mi", redeployTime: "4h", assignments30d: 0,  idleDays: 7 },
];

/* ── COLD-CHAIN SENSOR READINGS ────────────────────────────── */
const COLD_CHAIN_DATA = [
  { id: "SENS-001", shipmentId: "SHP-001", sensorId: "SN-A1", temp: 5.2,   minTemp: 2,   maxTemp: 8,   humidity: 68, battery: 87, timestamp: "2025-07-14 11:45", gps: "32.1°N, 95.8°W", doorStatus: "Closed", status: "Normal",   acknowledged: false },
  { id: "SENS-002", shipmentId: "SHP-006", sensorId: "SN-B2", temp: 11.8,  minTemp: 4,   maxTemp: 10,  humidity: 74, battery: 61, timestamp: "2025-07-14 12:00", gps: "33.4°N, 112.0°W",doorStatus: "Closed", status: "Warning",  acknowledged: false },
  { id: "SENS-003", shipmentId: "SHP-008", sensorId: "SN-C3", temp: 2.1,   minTemp: 0,   maxTemp: 4,   humidity: 90, battery: 45, timestamp: "2025-07-14 11:55", gps: "37.8°N, 122.3°W",doorStatus: "Closed", status: "Normal",   acknowledged: false },
  { id: "SENS-004", shipmentId: "SHP-010", sensorId: "SN-D4", temp: 23.6,  minTemp: 15,  maxTemp: 20,  humidity: 55, battery: 72, timestamp: "2025-07-14 12:10", gps: "29.7°N, 95.4°W", doorStatus: "Open",   status: "Critical", acknowledged: false },
  { id: "SENS-005", shipmentId: "SHP-011", sensorId: "SN-E5", temp: 4.5,   minTemp: 2,   maxTemp: 8,   humidity: 71, battery: 93, timestamp: "2025-07-14 12:05", gps: "32.7°N, 117.2°W",doorStatus: "Closed", status: "Normal",   acknowledged: false },
  { id: "SENS-006", shipmentId: "SHP-012", sensorId: "SN-F6", temp: -12.3, minTemp: -18, maxTemp: -15, humidity: 82, battery: 38, timestamp: "2025-07-14 12:15", gps: "26.2°N, 98.2°W", doorStatus: "Closed", status: "Critical", acknowledged: false },
  { id: "SENS-007", shipmentId: "SHP-001", sensorId: "SN-A2", temp: 6.9,   minTemp: 2,   maxTemp: 8,   humidity: 65, battery: 80, timestamp: "2025-07-14 12:20", gps: "31.8°N, 94.1°W", doorStatus: "Closed", status: "Normal",   acknowledged: false },
  { id: "SENS-008", shipmentId: "SHP-006", sensorId: "SN-B3", temp: 12.9,  minTemp: 4,   maxTemp: 10,  humidity: 78, battery: 55, timestamp: "2025-07-14 12:25", gps: "33.5°N, 111.8°W",doorStatus: "Open",   status: "Critical", acknowledged: false },
  { id: "SENS-009", shipmentId: "SHP-008", sensorId: "SN-C4", temp: 3.8,   minTemp: 0,   maxTemp: 4,   humidity: 88, battery: 42, timestamp: "2025-07-14 12:30", gps: "37.6°N, 121.9°W",doorStatus: "Closed", status: "Normal",   acknowledged: false },
  { id: "SENS-010", shipmentId: "SHP-010", sensorId: "SN-D5", temp: 26.1,  minTemp: 15,  maxTemp: 20,  humidity: 50, battery: 68, timestamp: "2025-07-14 12:35", gps: "29.8°N, 95.2°W", doorStatus: "Open",   status: "Critical", acknowledged: false },
];

/* ── ACTION CENTRE ─────────────────────────────────────────── */
const ACTIONS_DATA = [
  { id: "ACT-001", priority: "Critical", type: "Reroute",          related: "SHP-001", reason: "Severe storm blocking I-10 West. Immediate reroute required.",       team: "Operations",    deadline: "2025-07-14 14:00", status: "Pending",   snoozed: false },
  { id: "ACT-002", priority: "Critical", type: "Cold Chain Alert", related: "SHP-010", reason: "Temperature sensor SN-D4 reading 23.6°C — exceeds 20°C limit.",     team: "Quality",       deadline: "2025-07-14 13:00", status: "Pending",   snoozed: false },
  { id: "ACT-003", priority: "Critical", type: "Cold Chain Alert", related: "SHP-012", reason: "Frozen cargo SHP-012 sensor reads −12.3°C — above −15°C minimum.",   team: "Quality",       deadline: "2025-07-14 13:30", status: "Pending",   snoozed: false },
  { id: "ACT-004", priority: "High",     type: "Redeploy Asset",   related: "VH-104",  reason: "Refrigerated van idle in Phoenix near affected SHP-006 cold cargo.",  team: "Fleet",         deadline: "2025-07-14 15:00", status: "Pending",   snoozed: false },
  { id: "ACT-005", priority: "High",     type: "Carrier Switch",   related: "SHP-002", reason: "PacificShip Lines unavailable at LA port due to strike.",             team: "Procurement",   deadline: "2025-07-14 16:00", status: "Pending",   snoozed: false },
  { id: "ACT-006", priority: "High",     type: "Customs Docs",     related: "SHP-007", reason: "Laredo crossing restrictions. Verify all export documentation.",       team: "Compliance",    deadline: "2025-07-14 14:30", status: "Pending",   snoozed: false },
  { id: "ACT-007", priority: "High",     type: "Reroute",          related: "SHP-003", reason: "Border restrictions on I-35. Alternate route via US-277 available.",  team: "Operations",    deadline: "2025-07-14 15:30", status: "Pending",   snoozed: false },
  { id: "ACT-008", priority: "Medium",   type: "Redeploy Asset",   related: "VH-102",  reason: "Flatbed truck idle in Memphis. SHP-004 requires capacity support.",   team: "Fleet",         deadline: "2025-07-15 08:00", status: "Pending",   snoozed: false },
  { id: "ACT-009", priority: "Medium",   type: "Fuel Check",       related: "VH-107",  reason: "Refrigerated truck VH-107 fuel at 44%. Schedule refuel before Portland.",team: "Fleet",      deadline: "2025-07-14 18:00", status: "Pending",   snoozed: false },
  { id: "ACT-010", priority: "Medium",   type: "Customer Notice",  related: "SHP-005", reason: "Port strike may delay SHP-005 by 24+ hours. Notify customer.",        team: "Customer Svc",  deadline: "2025-07-14 17:00", status: "Pending",   snoozed: false },
  { id: "ACT-011", priority: "Low",      type: "Inspection",       related: "SHP-009", reason: "I-80 closure adds minor delay. Schedule delivery window update.",     team: "Ops Support",   deadline: "2025-07-15 12:00", status: "Pending",   snoozed: false },
  { id: "ACT-012", priority: "Low",      type: "Report",           related: "ALL",     reason: "Generate end-of-day disruption impact report for management.",        team: "Management",    deadline: "2025-07-14 20:00", status: "Pending",   snoozed: false },
];

/* ── AUDIT LOG ─────────────────────────────────────────────── */
const AUDIT_LOG_DATA = [
  { id: "LOG-001", timestamp: "2025-07-14 08:15", action: "Disruption Detected", entity: "System",    prev: "No disruption",      next: "Severe Storm activated",         user: "System Auto" },
  { id: "LOG-002", timestamp: "2025-07-14 08:22", action: "Alert Raised",        entity: "SHP-010",   prev: "Status: On Time",    next: "Status: At Risk",                user: "System Auto" },
  { id: "LOG-003", timestamp: "2025-07-14 08:45", action: "Carrier Flagged",     entity: "OceanFreight Co", prev: "Available",   next: "Unavailable – Storm",            user: "System Auto" },
  { id: "LOG-004", timestamp: "2025-07-14 09:10", action: "Action Created",      entity: "ACT-001",   prev: "—",                  next: "Reroute SHP-001 – Critical",     user: "J. Martinez (Ops)" },
  { id: "LOG-005", timestamp: "2025-07-14 09:30", action: "Cold Chain Alert",    entity: "SENS-004",  prev: "Temp: 17.2°C",       next: "Temp: 23.6°C – Critical",        user: "System Auto" },
  { id: "LOG-006", timestamp: "2025-07-14 10:00", action: "Fleet Status Update", entity: "VH-104",    prev: "Status: Available",  next: "Status: Idle",                   user: "K. Patel (Fleet)" },
  { id: "LOG-007", timestamp: "2025-07-14 10:15", action: "Action Created",      entity: "ACT-004",   prev: "—",                  next: "Redeploy VH-104 – High Priority",user: "K. Patel (Fleet)" },
  { id: "LOG-008", timestamp: "2025-07-14 10:45", action: "Sensor Alert",        entity: "SENS-006",  prev: "Temp: −16.1°C",      next: "Temp: −12.3°C – Critical",       user: "System Auto" },
  { id: "LOG-009", timestamp: "2025-07-14 11:00", action: "Route Review",        entity: "SHP-003",   prev: "Route: I-35 North",  next: "Under review – Border restriction",user: "R. Chen (Ops)" },
  { id: "LOG-010", timestamp: "2025-07-14 11:30", action: "Dashboard Loaded",    entity: "System",    prev: "—",                  next: "Control tower initialised",       user: "System Auto" },
];

/* ── ALERTS & NOTIFICATIONS DATA ──────────────────────────── */
const ALERTS_DATA = [
  {
    id: "ALT-001",
    type: "temperature_breach",
    category: "Critical Temperature Breach",
    priority: "critical",
    title: "Critical Temp Excursion: Medical Supplies (SHP-010)",
    message: "Sensor SN-D4 in Houston recorded 23.6°C — exceeds 20.0°C maximum threshold. Cargo integrity at immediate risk.",
    shipmentId: "SHP-010",
    assetId: "VH-103",
    triggeredAt: "2025-07-14 12:10 UTC",
    status: "open",
    acknowledgedAt: null,
    acknowledgedBy: null,
    resolvedAt: null,
    resolvedBy: null
  },
  {
    id: "ALT-002",
    type: "disruption_event",
    category: "Disruption Event",
    priority: "critical",
    title: "Severe Weather Disruption: Gulf Coast Category 3 Storm",
    message: "Category 3 storm active in Houston port zone. I-10 West blocked. 5 active shipments affected ($2.4M value).",
    shipmentId: "SHP-001",
    assetId: "VH-101",
    disruptionId: "severe_storm",
    triggeredAt: "2025-07-14 06:15 UTC",
    status: "open",
    acknowledgedAt: null,
    acknowledgedBy: null,
    resolvedAt: null,
    resolvedBy: null
  },
  {
    id: "ALT-003",
    type: "shipment_delay",
    category: "Shipment Delay",
    priority: "warning",
    title: "Significant Delay: Electronics Consignment SHP-002",
    message: "Port of Los Angeles strike causing 18-hour estimated transit delay. SLA deadline jeopardized.",
    shipmentId: "SHP-002",
    assetId: "VH-105",
    triggeredAt: "2025-07-14 09:30 UTC",
    status: "open",
    acknowledgedAt: null,
    acknowledgedBy: null,
    resolvedAt: null,
    resolvedBy: null
  },
  {
    id: "ALT-004",
    type: "missed_eta",
    category: "Missed ETA",
    priority: "warning",
    title: "SLA Deadline Breach Risk: Industrial Machinery SHP-004",
    message: "I-80 bridge closure forced detour via US-30. ETA delayed past scheduled customer delivery window.",
    shipmentId: "SHP-004",
    assetId: "VH-102",
    triggeredAt: "2025-07-14 10:05 UTC",
    status: "open",
    acknowledgedAt: null,
    acknowledgedBy: null,
    resolvedAt: null,
    resolvedBy: null
  },
  {
    id: "ALT-005",
    type: "idle_vehicle",
    category: "Idle Vehicle",
    priority: "warning",
    title: "Underutilised Asset: Heavy Hauler VH-108 Idle 7 Days",
    message: "VH-108 parked in Kansas City, MO incurring $280/day holding penalty. Reassignment recommended.",
    shipmentId: null,
    assetId: "VH-108",
    triggeredAt: "2025-07-14 07:00 UTC",
    status: "open",
    acknowledgedAt: null,
    acknowledgedBy: null,
    resolvedAt: null,
    resolvedBy: null
  },
  {
    id: "ALT-006",
    type: "capacity_shortage",
    category: "Capacity Shortage",
    priority: "warning",
    title: "High Load Factor: Tanker Truck VH-103 at 96% Capacity",
    message: "VH-103 loaded with 9,600 kg chemical goods (limit 10,000 kg). Additional cargo weight prohibited.",
    shipmentId: "SHP-010",
    assetId: "VH-103",
    triggeredAt: "2025-07-14 11:20 UTC",
    status: "acknowledged",
    acknowledgedAt: "2025-07-14 11:45 UTC",
    acknowledgedBy: "C. Rodriguez (Driver)",
    resolvedAt: null,
    resolvedBy: null
  },
  {
    id: "ALT-007",
    type: "high_risk_cargo",
    category: "High-Risk Cargo",
    priority: "critical",
    title: "Hazmat Cargo Rerouting Alert: Chemicals SHP-003",
    message: "Border crossing inspection delays in Laredo, TX impacting high-consequence hazardous cargo.",
    shipmentId: "SHP-003",
    assetId: null,
    triggeredAt: "2025-07-14 08:40 UTC",
    status: "open",
    acknowledgedAt: null,
    acknowledgedBy: null,
    resolvedAt: null,
    resolvedBy: null
  },
  {
    id: "ALT-008",
    type: "temperature_breach",
    category: "Critical Temperature Breach",
    priority: "critical",
    title: "Frozen Food Temp Elevation: SHP-012 Sensor Reading −12.3°C",
    message: "Sensor SN-F6 in Rio Grande Valley reading above −15.0°C cold-chain floor limit.",
    shipmentId: "SHP-012",
    assetId: null,
    triggeredAt: "2025-07-14 12:15 UTC",
    status: "open",
    acknowledgedAt: null,
    acknowledgedBy: null,
    resolvedAt: null,
    resolvedBy: null
  }
];

